/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen.pkg1_marcelarivera;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mvrivera
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CrearCuenta = new javax.swing.JFrame();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        AlumnoNormal = new javax.swing.JFrame();
        contra_normal = new javax.swing.JTextField();
        edad_normal = new javax.swing.JTextField();
        carrera_normal = new javax.swing.JTextField();
        nombre_normal = new javax.swing.JTextField();
        cuenta_normal = new javax.swing.JTextField();
        lugar_normal = new javax.swing.JTextField();
        usuario_normal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        aprendizaje_normal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Tutor = new javax.swing.JFrame();
        carrera_tutor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        nombre_tutor = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cuenta_tutor = new javax.swing.JTextField();
        lugar_tutor = new javax.swing.JTextField();
        usuario_tutor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        contra_tutor = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        edad_tutor = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        musica = new javax.swing.JCheckBox();
        Mate = new javax.swing.JCheckBox();
        espa = new javax.swing.JCheckBox();
        ccnn = new javax.swing.JCheckBox();
        ccss = new javax.swing.JCheckBox();
        progra = new javax.swing.JCheckBox();
        sociologia = new javax.swing.JCheckBox();
        antro = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        ganancia_tutor = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        nivel_tutor = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        Login = new javax.swing.JFrame();
        usuario_login = new javax.swing.JTextField();
        contra_login = new javax.swing.JPasswordField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        MenuAlumnoNormal = new javax.swing.JFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaAlumnos = new javax.swing.JTable();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        modi_carrera_normal1 = new javax.swing.JTextField();
        modi_nombre_normal = new javax.swing.JTextField();
        modi_lugar_normal1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        modi_edad_normal1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        modi_cuenta_normal1 = new javax.swing.JTextField();
        modi_aprendizaje_normal1 = new javax.swing.JTextField();
        modi_usuario_normal1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        modi_contra_normal1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaExamen = new javax.swing.JTable();
        jButton14 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        tuto_fecha = new datechooser.beans.DateChooserCombo();
        tuto_hora = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        tuto_aula = new javax.swing.JTextField();
        tuto_clase = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaTutores = new javax.swing.JTable();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        tuto_tema = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        Examen = new javax.swing.JFrame();
        exam_clase1 = new javax.swing.JComboBox<>();
        exam_tema = new javax.swing.JTextField();
        exam_puntaj = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        MenuTutor = new javax.swing.JFrame();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Tablatutor2 = new javax.swing.JTable();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        modi_carrera_normal2 = new javax.swing.JTextField();
        modi_nombre_normal1 = new javax.swing.JTextField();
        modi_lugar_normal2 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        modi_edad_normal2 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        modi_cuenta_normal2 = new javax.swing.JTextField();
        modi_aprendizaje_normal2 = new javax.swing.JTextField();
        modi_usuario_normal2 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        modi_contra_normal2 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        TablaTutores1 = new javax.swing.JTable();
        jButton22 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jButton4.setText("Registrarse como alumno normal");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Registrar como tutor");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CrearCuentaLayout = new javax.swing.GroupLayout(CrearCuenta.getContentPane());
        CrearCuenta.getContentPane().setLayout(CrearCuentaLayout);
        CrearCuentaLayout.setHorizontalGroup(
            CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearCuentaLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        CrearCuentaLayout.setVerticalGroup(
            CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearCuentaLayout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(57, 57, 57)
                .addComponent(jButton5)
                .addGap(92, 92, 92))
        );

        jLabel1.setText("Nombre:");

        jLabel2.setText("Edad:");

        jLabel3.setText("Carrera:");

        jLabel4.setText("Lugar de nacimiento:");

        jLabel5.setText("Numero de cuenta:");

        jLabel6.setText("Usuario:");

        jLabel7.setText("Contraseña:");

        jButton6.setText("Agregar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel8.setText("Nivel Aprendizaje:");

        javax.swing.GroupLayout AlumnoNormalLayout = new javax.swing.GroupLayout(AlumnoNormal.getContentPane());
        AlumnoNormal.getContentPane().setLayout(AlumnoNormalLayout);
        AlumnoNormalLayout.setHorizontalGroup(
            AlumnoNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlumnoNormalLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(AlumnoNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton6)
                    .addGroup(AlumnoNormalLayout.createSequentialGroup()
                        .addGroup(AlumnoNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(AlumnoNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombre_normal)
                            .addComponent(edad_normal)
                            .addComponent(carrera_normal)
                            .addComponent(lugar_normal, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                            .addComponent(cuenta_normal)
                            .addComponent(usuario_normal)
                            .addComponent(contra_normal)
                            .addComponent(aprendizaje_normal))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        AlumnoNormalLayout.setVerticalGroup(
            AlumnoNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlumnoNormalLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(AlumnoNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AlumnoNormalLayout.createSequentialGroup()
                        .addGroup(AlumnoNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(AlumnoNormalLayout.createSequentialGroup()
                                .addGroup(AlumnoNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(AlumnoNormalLayout.createSequentialGroup()
                                        .addGroup(AlumnoNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(AlumnoNormalLayout.createSequentialGroup()
                                                .addGroup(AlumnoNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(nombre_normal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel1))
                                                .addGap(18, 18, 18)
                                                .addComponent(edad_normal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel2))
                                        .addGap(18, 18, 18)
                                        .addComponent(carrera_normal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(AlumnoNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lugar_normal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addComponent(cuenta_normal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addComponent(usuario_normal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(AlumnoNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contra_normal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(AlumnoNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aprendizaje_normal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(20, 20, 20)
                .addComponent(jButton6)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        jLabel9.setText("Usuario:");

        jLabel10.setText("Contraseña:");

        jLabel11.setText("Nombre:");

        jLabel12.setText("Edad:");

        jLabel13.setText("Carrera:");

        jLabel14.setText("Lugar de nacimiento:");

        jLabel15.setText("Numero de cuenta:");

        musica.setText("Musica");

        Mate.setText("Matematicas");

        espa.setText("Español");

        ccnn.setText("CCNN");

        ccss.setText("CCSS");

        progra.setText("Programacion");

        sociologia.setText("Sociologia");

        antro.setText("Antropologia");

        jLabel16.setText("Clases Dadas:");

        jButton7.setText("Agregar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel17.setText("Ganancia:");

        jLabel18.setText("Nivel de enseñanza:");

        javax.swing.GroupLayout TutorLayout = new javax.swing.GroupLayout(Tutor.getContentPane());
        Tutor.getContentPane().setLayout(TutorLayout);
        TutorLayout.setHorizontalGroup(
            TutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TutorLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(TutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TutorLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addGroup(TutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TutorLayout.createSequentialGroup()
                                .addGroup(TutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Mate)
                                    .addComponent(espa)
                                    .addComponent(ccss)
                                    .addComponent(ccnn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(TutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(antro)
                                    .addComponent(sociologia)
                                    .addComponent(progra)
                                    .addComponent(musica)))
                            .addGroup(TutorLayout.createSequentialGroup()
                                .addGap(288, 288, 288)
                                .addComponent(jButton7))))
                    .addGroup(TutorLayout.createSequentialGroup()
                        .addGroup(TutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(TutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nombre_tutor)
                                .addComponent(edad_tutor)
                                .addComponent(carrera_tutor)
                                .addComponent(lugar_tutor)
                                .addComponent(cuenta_tutor)
                                .addComponent(usuario_tutor)
                                .addComponent(contra_tutor, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ganancia_tutor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nivel_tutor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        TutorLayout.setVerticalGroup(
            TutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TutorLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(TutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(TutorLayout.createSequentialGroup()
                        .addGroup(TutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(TutorLayout.createSequentialGroup()
                                .addGroup(TutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(TutorLayout.createSequentialGroup()
                                        .addGroup(TutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(TutorLayout.createSequentialGroup()
                                                .addGroup(TutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(nombre_tutor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel11))
                                                .addGap(18, 18, 18)
                                                .addComponent(edad_tutor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel12))
                                        .addGap(18, 18, 18)
                                        .addComponent(carrera_tutor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(TutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lugar_tutor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addComponent(cuenta_tutor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addComponent(usuario_tutor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(TutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contra_tutor, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(12, 12, 12)
                .addGroup(TutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(ganancia_tutor, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nivel_tutor, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(TutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mate)
                    .addComponent(musica)
                    .addComponent(jLabel16))
                .addGap(2, 2, 2)
                .addGroup(TutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(espa)
                    .addComponent(progra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ccss)
                    .addComponent(sociologia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ccnn)
                    .addComponent(antro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7)
                .addGap(53, 53, 53))
        );

        jLabel19.setText("Usuario:");

        jLabel20.setText("Contraseña:");

        jButton8.setText("Volver");

        jButton9.setText("Entrar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login.getContentPane());
        Login.getContentPane().setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addGap(28, 28, 28)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton9))
                    .addComponent(usuario_login)
                    .addComponent(contra_login, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuario_login, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(26, 26, 26)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contra_login, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addGap(17, 17, 17))
        );

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        TablaAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Edad", "Carrera", "Lugar Nacimiento", "Numero cuenta", "Usuario", "Contraseña", "Nivel Aprendizaje"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaAlumnos);

        jButton10.setText("Modificar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Eliminar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel21.setText("Nombre:");

        jLabel22.setText("Edad:");

        jLabel23.setText("Carrera:");

        jLabel24.setText("Lugar de nacimiento:");

        jLabel25.setText("Usuario:");

        jLabel26.setText("Contraseña:");

        jLabel27.setText("Nivel Aprendizaje:");

        jLabel28.setText("Numero de cuenta:");

        jLabel29.setText("ALUMNOS NORMALES");

        jButton16.setText("Salir Login");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(modi_carrera_normal1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(modi_edad_normal1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modi_nombre_normal, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modi_lugar_normal1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(modi_usuario_normal1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                            .addComponent(modi_cuenta_normal1)
                            .addComponent(modi_contra_normal1)
                            .addComponent(modi_aprendizaje_normal1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(106, 106, 106))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton16)
                        .addGap(40, 40, 40))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jButton16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modi_nombre_normal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modi_edad_normal1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modi_carrera_normal1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modi_lugar_normal1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel25)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel28)
                                    .addComponent(modi_cuenta_normal1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(modi_usuario_normal1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(modi_contra_normal1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel26))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton11)
                                .addGap(7, 7, 7)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modi_aprendizaje_normal1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27)
                            .addComponent(jButton10))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Modificar Datos", jPanel1);

        TablaExamen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Materia", "Tema", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TablaExamen);

        jButton14.setText("Hacer Examen");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton14)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Examenes Pendientes", jPanel3);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Materia", "Tema", "Valor", "Nota Obtenida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1009, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Examenes Resueltos", jPanel4);

        tuto_hora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  -------------------------------------", "7:00 am", "8:30 am", "10:10 am", "11:30 am", "1:00 pm", "2:20 pm", "3:40 pm", "5:10 pm", "7:00 pm", " ", " " }));
        tuto_hora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuto_horaActionPerformed(evt);
            }
        });

        jLabel30.setText("Hora:");

        jLabel31.setText("Fecha:");

        jLabel32.setText("Aula:");

        tuto_clase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  -------------------------------------", "Matematicas", "Español", "CCSS", "CCNN", "Musica", "Programacion", "Sociologia", "Antropologia" }));

        jLabel33.setText("Clase:");

        TablaTutores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Edad", "Carrera", "Lugar Nacimiento", "Numero Cuenta", "Usuario", "Contraseña", "Nivel Enseñanza"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(TablaTutores);

        jButton12.setText("Agregar Tutor");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Agregar tutoria");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jLabel34.setText("Tema:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 861, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel31)
                                        .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(35, 35, 35))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel34)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tuto_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tuto_aula, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tuto_clase, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tuto_hora, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tuto_tema)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton13))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel32)
                                    .addComponent(tuto_aula, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel31)
                                    .addComponent(tuto_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tuto_hora, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel30))
                                .addGap(18, 18, 18)
                                .addComponent(tuto_clase, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel33))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tuto_tema, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34))
                        .addGap(38, 38, 38)
                        .addComponent(jButton12)))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reservar Tutorias", jPanel5);

        javax.swing.GroupLayout MenuAlumnoNormalLayout = new javax.swing.GroupLayout(MenuAlumnoNormal.getContentPane());
        MenuAlumnoNormal.getContentPane().setLayout(MenuAlumnoNormalLayout);
        MenuAlumnoNormalLayout.setHorizontalGroup(
            MenuAlumnoNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuAlumnoNormalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        MenuAlumnoNormalLayout.setVerticalGroup(
            MenuAlumnoNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuAlumnoNormalLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        exam_clase1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  -------------------------------------", "Matematicas", "Español", "CCSS", "CCNN", "Musica", "Programacion", "Sociologia", "Antropologia" }));
        exam_clase1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exam_clase1ActionPerformed(evt);
            }
        });

        jLabel35.setText("CREAR EXAMEN");

        jLabel36.setText("Clase:");

        jLabel37.setText("Tema:");

        jLabel38.setText("Puntaje:");

        jButton15.setText("Crear");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ExamenLayout = new javax.swing.GroupLayout(Examen.getContentPane());
        Examen.getContentPane().setLayout(ExamenLayout);
        ExamenLayout.setHorizontalGroup(
            ExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExamenLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(ExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel36)
                    .addComponent(jLabel37)
                    .addComponent(jLabel38))
                .addGap(33, 33, 33)
                .addGroup(ExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton15)
                        .addGroup(ExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(exam_clase1, 0, 199, Short.MAX_VALUE)
                            .addComponent(exam_tema)
                            .addComponent(exam_puntaj))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        ExamenLayout.setVerticalGroup(
            ExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExamenLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(ExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel38)
                    .addGroup(ExamenLayout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(exam_clase1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36))
                        .addGap(18, 18, 18)
                        .addGroup(ExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(exam_tema, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37))
                        .addGap(18, 18, 18)
                        .addComponent(exam_puntaj, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jButton15)
                .addGap(55, 55, 55))
        );

        jTabbedPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane2MouseClicked(evt);
            }
        });

        Tablatutor2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Edad", "Carrera", "Lugar Nacimiento", "Numero cuenta", "Usuario", "Contraseña", "Nivel Enseñanza"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(Tablatutor2);

        jButton17.setText("Modificar");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setText("Eliminar");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jLabel39.setText("Nombre:");

        jLabel40.setText("Edad:");

        jLabel41.setText("Carrera:");

        jLabel42.setText("Lugar de nacimiento:");

        jLabel43.setText("Usuario:");

        jLabel44.setText("Contraseña:");

        jLabel45.setText("Nivel Aprendizaje:");

        jLabel46.setText("Numero de cuenta:");

        jLabel47.setText("ALUMNOS TUTORES");

        jButton19.setText("Salir Login");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel39)
                            .addComponent(jLabel40)
                            .addComponent(jLabel41)
                            .addComponent(jLabel42))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(modi_carrera_normal2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(modi_edad_normal2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modi_nombre_normal1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modi_lugar_normal2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel46)
                            .addComponent(jLabel43)
                            .addComponent(jLabel44)
                            .addComponent(jLabel45))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(modi_usuario_normal2, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                            .addComponent(modi_cuenta_normal2)
                            .addComponent(modi_contra_normal2)
                            .addComponent(modi_aprendizaje_normal2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(106, 106, 106))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel47)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton19)
                        .addGap(40, 40, 40))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(jButton19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modi_nombre_normal1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modi_edad_normal2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel40))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modi_carrera_normal2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel41))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modi_lugar_normal2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel42)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel43)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel46)
                                    .addComponent(modi_cuenta_normal2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(modi_usuario_normal2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(modi_contra_normal2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel44))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton18)
                                .addGap(7, 7, 7)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modi_aprendizaje_normal2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel45)
                            .addComponent(jButton17))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Modificar Datos", jPanel2);

        TablaTutores1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Edad", "Carrera", "Lugar Nacimiento", "Numero Cuenta", "Usuario", "Contraseña", "Nivel Enseñanza"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane8.setViewportView(TablaTutores1);

        jButton22.setText("Dar tutoria");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 1110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton22)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Dar Tutoria", jPanel8);

        javax.swing.GroupLayout MenuTutorLayout = new javax.swing.GroupLayout(MenuTutor.getContentPane());
        MenuTutor.getContentPane().setLayout(MenuTutorLayout);
        MenuTutorLayout.setHorizontalGroup(
            MenuTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuTutorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        MenuTutorLayout.setVerticalGroup(
            MenuTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuTutorLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Crear cuenta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Crear examen");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Login");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jButton1)
                .addGap(47, 47, 47)
                .addComponent(jButton3)
                .addGap(45, 45, 45)
                .addComponent(jButton2)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CrearCuenta.pack();
        this.setVisible(false);
        CrearCuenta.setLocationRelativeTo(this);
        CrearCuenta.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    int usuarioUsado;
    ArrayList<Alumno> alumnos = new ArrayList();

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        alumnos.add(new Alumno_normal(Integer.parseInt(edad_normal.getText()), nombre_normal.getText(),
                carrera_normal.getText(), lugar_normal.getText(), usuario_normal.getText(),
                contra_normal.getText(), Integer.parseInt(edad_normal.getText()), Integer.parseInt(cuenta_normal.getText())));
        JOptionPane.showMessageDialog(this, "Se ingreso correctamente");
        
        AlumnoNormal.pack();
        this.pack();
        AlumnoNormal.setVisible(false);
        this.setLocationRelativeTo(this);
        this.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        alumnos.add(new Tutor(Double.parseDouble(ganancia_tutor.getText()), Integer.parseInt(nivel_tutor.getText()), nombre_tutor.getText(), carrera_tutor.getText(), lugar_tutor.getText(), usuario_tutor.getText(), contra_tutor.getText(),
                Integer.parseInt(edad_tutor.getText()), Integer.parseInt(cuenta_tutor.getText())));
        if (Mate.isSelected()) {
            ((Tutor) alumnos.get(alumnos.size() - 1)).getClasesDadas().add("Matematicas");
            System.out.println(":D");
        }
        if (sociologia.isSelected()) {
            ((Tutor) alumnos.get(alumnos.size() - 1)).getClasesDadas().add("Sociologia");
        }
        if (espa.isSelected()) {
            ((Tutor) alumnos.get(alumnos.size() - 1)).getClasesDadas().add("Español");
        }
        if (ccnn.isSelected()) {
            ((Tutor) alumnos.get(alumnos.size() - 1)).getClasesDadas().add("CCNN");
        }
        if (ccss.isSelected()) {
            ((Tutor) alumnos.get(alumnos.size() - 1)).getClasesDadas().add("CCSS");
        }
        if (progra.isSelected()) {
            ((Tutor) alumnos.get(alumnos.size() - 1)).getClasesDadas().add("Programacion");
        }
        if (musica.isSelected()) {
            ((Tutor) alumnos.get(alumnos.size() - 1)).getClasesDadas().add("Musica");
        }
        if (antro.isSelected()) {
            ((Tutor) alumnos.get(alumnos.size() - 1)).getClasesDadas().add("Antropologia");
        }
        
        JOptionPane.showMessageDialog(this, "Se ingreso correctamente");
        
        Tutor.pack();
        this.pack();
        Tutor.setVisible(false);
        this.setLocationRelativeTo(this);
        this.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        CrearCuenta.pack();
        AlumnoNormal.pack();
        CrearCuenta.setVisible(false);
        AlumnoNormal.setLocationRelativeTo(this);
        AlumnoNormal.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        CrearCuenta.pack();
        Tutor.pack();
        CrearCuenta.setVisible(false);
        Tutor.setLocationRelativeTo(this);
        Tutor.setVisible(true);
        

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        int cont = 0;
        for (Alumno i : alumnos) {
            if ((usuario_login.getText().equals(i.getUsuario())) && (contra_login.getText().equals(i.getContra()))) {
                usuarioUsado = cont;
                if (i instanceof Tutor) {
                    Login.pack();
                    MenuTutor.pack();
                    this.Login.setVisible(true);
                    MenuTutor.setLocationRelativeTo(this);
                    MenuTutor.setVisible(true);
                    llenarTabla();
                }
                if (i instanceof Alumno_normal) {
                    Login.pack();
                    MenuAlumnoNormal.pack();
                    this.Login.setVisible(true);
                    MenuAlumnoNormal.setLocationRelativeTo(this);
                    MenuAlumnoNormal.setVisible(true);
                    llenarTabla();
                }
                break;
            }
            cont++;
        }

    }//GEN-LAST:event_jButton9ActionPerformed
    
    public void llenarTabla() {
        DefaultTableModel m = (DefaultTableModel) TablaAlumnos.getModel();
        DefaultTableModel m2 = (DefaultTableModel) TablaTutores.getModel();
        DefaultTableModel m3 = (DefaultTableModel) TablaTutores1.getModel();
        
        for (int i = m.getRowCount() - 1; i >= 0; i--) {
            m3.removeRow(i);
        }
        for (int i = m.getRowCount() - 1; i >= 0; i--) {
            m.removeRow(i);
        }
        for (int i = m2.getRowCount() - 1; i >= 0; i--) {
            m2.removeRow(i);
        }
         for (Alumno i : alumnos) {
            if (i instanceof ) {
                Object[] pe = {i.getNombre(), i.getEdad(), i.getCarrera(), i.getLugarNacimiento(), i.getN_cuenta(), i.getUsuario(), i.getContra(), ((Alumno_normal) i).getN_aprendizaje()};
                m.addRow(pe);
            }
        }
        for (Alumno i : alumnos) {
            if (i instanceof Alumno_normal) {
                Object[] pe = {i.getNombre(), i.getEdad(), i.getCarrera(), i.getLugarNacimiento(), i.getN_cuenta(), i.getUsuario(), i.getContra(), ((Alumno_normal) i).getN_aprendizaje()};
                m.addRow(pe);
            }
        }
        for (Alumno i : alumnos) {
            if (i instanceof Tutor) {
                Object[] pe = {i.getNombre(), i.getEdad(), i.getCarrera(), i.getLugarNacimiento(), i.getN_cuenta(), i.getUsuario(), i.getContra(), ((Tutor) i).getN_enseña()};
                m2.addRow(pe);
            }
        }
        TablaTutores.setModel(m2);
        TablaAlumnos.setModel(m);
        Tablatutor2.setModel(m2);
        
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        alumnos.add(new Alumno_normal(1, "manola", "ds", "dsd", "d", "123", 2, 4));
        alumnos.add(new Alumno_normal(1, "burra", "ds", "dsd", "patoo", "123", 2, 4));
        alumnos.add(new Tutor(45, 1, "puta", "ds", "dsd", "pato", "123", 2, 4));
        Login.pack();
        this.setVisible(false);
        Login.setLocationRelativeTo(this);
        Login.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        int filaEliminar = TablaAlumnos.getSelectedRow();
        if (filaEliminar >= 0) {
            System.out.println("dsa");
            alumnos.remove(filaEliminar);
            llenarTabla();
            
        }

    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        int filamodi = TablaAlumnos.getSelectedRow();
        System.out.println(filamodi);
        if (filamodi >= 0) {
            if (modi_nombre_normal.getText().equals("")) {
            } else {
                alumnos.get(filamodi).setNombre(modi_nombre_normal.getText());
            }
            
            if (modi_aprendizaje_normal1.getText().equals("")) {
            } else {
                ((Alumno_normal) alumnos.get(filamodi)).setN_aprendizaje(Integer.parseInt(modi_aprendizaje_normal1.getText()));
            }
            
            if (modi_carrera_normal1.getText().equals("")) {
            } else {
                alumnos.get(filamodi).setCarrera(modi_carrera_normal1.getText());
            }
            
            if (modi_contra_normal1.getText().equals("")) {
            } else {
                alumnos.get(filamodi).setContra(modi_contra_normal1.getText());
            }
            
            if (modi_cuenta_normal1.getText().equals("")) {
            } else {
                ((Alumno_normal) alumnos.get(filamodi)).setN_cuenta(Integer.parseInt(modi_cuenta_normal1.getText()));
            }
            if (modi_edad_normal1.getText().equals("")) {
            } else {
                ((Alumno_normal) alumnos.get(filamodi)).setEdad(Integer.parseInt(modi_edad_normal1.getText()));
            }
            if (modi_lugar_normal1.getText().equals("")) {
            } else {
                
                alumnos.get(filamodi).setLugarNacimiento(modi_lugar_normal1.getText());
            }
            if (modi_usuario_normal1.getText().equals("")) {
            } else {
                alumnos.get(filamodi).setUsuario(modi_usuario_normal1.getText());
            }
        }
        llenarTabla();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void tuto_horaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuto_horaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tuto_horaActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        String clase = (String) tuto_clase.getSelectedItem();
        String hora = (String) tuto_hora.getSelectedItem();
        int horaa = 0;
        if (hora.equals("7:00 am")) {
            horaa = 7;
        } else if (hora.equals("8:30 am")) {
            horaa = 8;
        } else if (hora.equals("10:10 am")) {
            horaa = 10;
        } else if (hora.equals("11:30 am")) {
            horaa = 11;
        } else if (hora.equals("1:00 pm")) {
            horaa = 1;
        } else if (hora.equals("2:20 pm")) {
            horaa = 2;
        } else if (hora.equals("3:40 pm")) {
            horaa = 3;
        } else if (hora.equals("5:10 pm")) {
            horaa = 5;
        } else if (hora.equals("7:00 pm")) {
            horaa = 7;
        }
        String[] tokens = tuto_fecha.getText().split("/");
        int mes = Integer.parseInt(tokens[0]);
        int dia = Integer.parseInt(tokens[1]);
        int anio = Integer.parseInt(tokens[2]);
        JOptionPane.showMessageDialog(this, "Su tutoria fue configurada a la perfecccion");
        
    }//GEN-LAST:event_jButton13ActionPerformed
    
    int tutor = -1, alumno = -1;
    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        
        tutor = TablaTutores.getSelectedRow();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Examen.pack();
        this.pack();
        MenuAlumnoNormal.setVisible(false);
        Examen.setLocationRelativeTo(this);
        Examen.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
    Random r = new Random();
    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        int posi = TablaExamen.getSelectedRow();
        int requerimiento = 1 + r.nextInt(99);
        if (posi > 0) {
            if (((Alumno_normal) alumnos.get(usuarioUsado)).getConocimiento() > requerimiento) {
                JOptionPane.showMessageDialog(this, "Aprobo el examen");
            } else {
                JOptionPane.showMessageDialog(this, "Reprobo el examen");
            }
        }
        

    }//GEN-LAST:event_jButton14ActionPerformed

    private void exam_clase1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exam_clase1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exam_clase1ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        String clase = (String) exam_clase1.getSelectedItem();
        String tema = exam_tema.getText();
        int valor = Integer.parseInt(exam_puntaj.getText());
        
        for (Alumno i : alumnos) {
            if (i instanceof Alumno_normal) {
                ((Alumno_normal) i).getExamenes().add(new Examenes(clase, tema, valor));
            }
        }
        JOptionPane.showMessageDialog(this, "Su examen se registro con exito");
        Examen.pack();
        this.pack();
        Examen.setVisible(false);
        this.setLocationRelativeTo(this);
        this.setVisible(true);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        MenuAlumnoNormal.pack();
        this.pack();
        MenuAlumnoNormal.setVisible(false);
        this.setLocationRelativeTo(this);
        this.setVisible(true);
        

    }//GEN-LAST:event_jButton16ActionPerformed

    private void jTabbedPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane2MouseClicked
    
        
    }//GEN-LAST:event_jTabbedPane2MouseClicked

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        MenuTutor.pack();
        this.pack();
        MenuTutor.setVisible(false);
        this.setLocationRelativeTo(this);
        this.setVisible(true);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        int filaEliminar = Tablatutor2.getSelectedRow();
        if (filaEliminar >= 0) {
            alumnos.remove(filaEliminar);
            llenarTabla();
            
        }

    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
       int filamodi = Tablatutor2.getSelectedRow();
        System.out.println(filamodi);
        if (filamodi >= 0) {
            if (modi_nombre_normal1.getText().equals("")) {
            } else {
                alumnos.get(filamodi).setNombre(modi_nombre_normal1.getText());
            }

            if (modi_carrera_normal2.getText().equals("")) {
            } else {
                alumnos.get(filamodi).setCarrera(modi_carrera_normal2.getText());
            }
            
            if (modi_contra_normal2.getText().equals("")) {
            } else {
                alumnos.get(filamodi).setContra(modi_contra_normal2.getText());
            }
            
            if (modi_cuenta_normal2.getText().equals("")) {
            } else {
                ((Alumno_normal) alumnos.get(filamodi)).setN_cuenta(Integer.parseInt(modi_cuenta_normal2.getText()));
            }
            if (modi_edad_normal2.getText().equals("")) {
            } else {
                ((Alumno_normal) alumnos.get(filamodi)).setEdad(Integer.parseInt(modi_edad_normal2.getText()));
            }
            if (modi_lugar_normal2.getText().equals("")) {
            } else {
                
                alumnos.get(filamodi).setLugarNacimiento(modi_lugar_normal2.getText());
            }
            if (modi_usuario_normal2.getText().equals("")) {
            } else {
                alumnos.get(filamodi).setUsuario(modi_usuario_normal2.getText());
            }
        }
        llenarTabla();
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame AlumnoNormal;
    private javax.swing.JFrame CrearCuenta;
    private javax.swing.JFrame Examen;
    private javax.swing.JFrame Login;
    private javax.swing.JCheckBox Mate;
    private javax.swing.JFrame MenuAlumnoNormal;
    private javax.swing.JFrame MenuTutor;
    private javax.swing.JTable TablaAlumnos;
    private javax.swing.JTable TablaExamen;
    private javax.swing.JTable TablaTutores;
    private javax.swing.JTable TablaTutores1;
    private javax.swing.JTable Tablatutor2;
    private javax.swing.JFrame Tutor;
    private javax.swing.JCheckBox antro;
    private javax.swing.JTextField aprendizaje_normal;
    private javax.swing.JTextField carrera_normal;
    private javax.swing.JTextField carrera_tutor;
    private javax.swing.JCheckBox ccnn;
    private javax.swing.JCheckBox ccss;
    private javax.swing.JPasswordField contra_login;
    private javax.swing.JTextField contra_normal;
    private javax.swing.JTextField contra_tutor;
    private javax.swing.JTextField cuenta_normal;
    private javax.swing.JTextField cuenta_tutor;
    private javax.swing.JTextField edad_normal;
    private javax.swing.JTextField edad_tutor;
    private javax.swing.JCheckBox espa;
    private javax.swing.JComboBox<String> exam_clase1;
    private javax.swing.JTextField exam_puntaj;
    private javax.swing.JTextField exam_tema;
    private javax.swing.JTextField ganancia_tutor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField lugar_normal;
    private javax.swing.JTextField lugar_tutor;
    private javax.swing.JTextField modi_aprendizaje_normal1;
    private javax.swing.JTextField modi_aprendizaje_normal2;
    private javax.swing.JTextField modi_carrera_normal1;
    private javax.swing.JTextField modi_carrera_normal2;
    private javax.swing.JTextField modi_contra_normal1;
    private javax.swing.JTextField modi_contra_normal2;
    private javax.swing.JTextField modi_cuenta_normal1;
    private javax.swing.JTextField modi_cuenta_normal2;
    private javax.swing.JTextField modi_edad_normal1;
    private javax.swing.JTextField modi_edad_normal2;
    private javax.swing.JTextField modi_lugar_normal1;
    private javax.swing.JTextField modi_lugar_normal2;
    private javax.swing.JTextField modi_nombre_normal;
    private javax.swing.JTextField modi_nombre_normal1;
    private javax.swing.JTextField modi_usuario_normal1;
    private javax.swing.JTextField modi_usuario_normal2;
    private javax.swing.JCheckBox musica;
    private javax.swing.JTextField nivel_tutor;
    private javax.swing.JTextField nombre_normal;
    private javax.swing.JTextField nombre_tutor;
    private javax.swing.JCheckBox progra;
    private javax.swing.JCheckBox sociologia;
    private javax.swing.JTextField tuto_aula;
    private javax.swing.JComboBox<String> tuto_clase;
    private datechooser.beans.DateChooserCombo tuto_fecha;
    private javax.swing.JComboBox<String> tuto_hora;
    private javax.swing.JTextField tuto_tema;
    private javax.swing.JTextField usuario_login;
    private javax.swing.JTextField usuario_normal;
    private javax.swing.JTextField usuario_tutor;
    // End of variables declaration//GEN-END:variables
}
